name: Run Semgrep reusable scan

on:
  push:
    branches:
      - main
      - develop
      - preprod
      - 'feat/**'

jobs:
  sast_scan:
    uses: Romano912/Romano912/orga_reusable_workflow/blob/main/security_reusable_sast_scan.yml@v2